### ISSUE TITLE
Excessive blank lines should be removed.

### ISSUE THREAD

**Issue by suatkarakusogludtek** [oguzhankertmen/RickAndMortyApp#2]
https://github.com/oguzhankertmen/RickAndMortyApp/blob/d114315f86ff16f1a4f0049d4fa07c07675d658d/RickAndMortyApp/ViewModel/queryViewModel.swift#L14

Maybe you can thing of integrating 'linting' library such as swiftlint.

**Comment by suatkarakusogludtek** [comment]
I haven't encountered the .swiftlint.yml file which linting rule definition resides in. 
Is there anything I am missing?

**Comment by oguzhankertmen** [comment]
Didn't pushed the file then, now I have pushed it.
